export const SITE = {
  website: "https://common-member.github.io",
  author: "common-member",
  profile: "https://github.com/common-member",
  desc: "Web開発における日々の学習記録をまとめる場所です。",
  title: "common-member's TIL",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/common-member/common-member.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;
